/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetSystemHealth - Get System Health
func GetSystemHealth(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
