/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// FiatConfirm - Confirm fiat request to GCash Cash Out
func FiatConfirm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FiatInConfirm - Confirm fiat request to GCash Cash In
func FiatInConfirm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FiatInRequest - Fiat request to GCash Cash In
func FiatInRequest(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FiatRequest - Create new fiat request to GCash Cash In
func FiatRequest(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCryptoPrice - Get PDAX crypto market prices
func GetCryptoPrice(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetIdToken - Get idToken
func GetIdToken(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetUserId - Get User ID
func GetUserId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetUserInfo - Get User Info
func GetUserInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRiskProfile - Post user's Risk Profile
func PostRiskProfile(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RegisterUser - Add new user
func RegisterUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SendOTP - Send OTP email
func SendOTP(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// TestLogin - Get idToken
func TestLogin(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
