/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatConfirmResponse struct {

	Message string `json:"message,omitempty"`

	TransactionId string `json:"transactionId,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Fee float32 `json:"fee,omitempty"`

	NetAmount float32 `json:"netAmount,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`
}
