/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginResponse struct {

	// added to headers for request validations
	IdToken string `json:"idToken,omitempty"`
}
