/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponse struct {

	ClientId string `json:"clientId,omitempty"`

	PartnerId string `json:"partnerId,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	UserInfo GetUserResponseUserInfo `json:"userInfo,omitempty"`

	Location GetUserResponseLocation `json:"location,omitempty"`

	Documents GetUserResponseDocuments `json:"documents,omitempty"`

	OtpStatus GetUserResponseOtpStatus `json:"otpStatus,omitempty"`

	Tier string `json:"tier,omitempty"`

	CryptoIn bool `json:"cryptoIn,omitempty"`

	CryptoOut bool `json:"cryptoOut,omitempty"`

	FiatIn bool `json:"fiatIn,omitempty"`

	FiatOut bool `json:"fiatOut,omitempty"`

	Trade bool `json:"trade,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	UpdatedAt *string `json:"updatedAt,omitempty"`
}
