/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatConfirm struct {

	Transid string `json:"transid"`

	Amount float32 `json:"amount"`
}
