/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatRequestResponseResponse struct {

	Head FiatRequestResponseResponseHead `json:"head,omitempty"`

	Body FiatRequestResponseResponseBody `json:"body,omitempty"`
}
