/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendOtpBody struct {

	OtpId string `json:"otpId"`

	Action string `json:"action"`

	FiatAmount float32 `json:"fiatAmount,omitempty"`

	CryptoToken string `json:"cryptoToken,omitempty"`

	CryptoTokenValue float32 `json:"cryptoTokenValue,omitempty"`

	DestinationAddress string `json:"destinationAddress,omitempty"`
}
