/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RegisterResponse struct {

	// added to headers for request validations
	Message string `json:"message,omitempty"`

	ClientId string `json:"clientId,omitempty"`
}
