/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponseLocation struct {

	Country string `json:"country,omitempty"`

	ZipCode string `json:"zipCode,omitempty"`

	Address string `json:"address,omitempty"`

	Region string `json:"region,omitempty"`

	City string `json:"city,omitempty"`
}
