/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponseDocuments struct {

	IdFrontUrl string `json:"idFrontUrl,omitempty"`

	IdBackUrl string `json:"idBackUrl,omitempty"`

	LivenessVideo string `json:"livenessVideo,omitempty"`

	DocumentId string `json:"documentId,omitempty"`

	IdFront string `json:"idFront,omitempty"`

	LivenessVideoUrl string `json:"livenessVideoUrl,omitempty"`

	IdBack string `json:"idBack,omitempty"`
}
