/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendOtpResponse struct {

	OtpId string `json:"otpId,omitempty"`

	Action string `json:"action,omitempty"`

	FiatAmount float32 `json:"fiatAmount,omitempty"`

	CryptoToken string `json:"cryptoToken,omitempty"`

	CryptoTokenValue float32 `json:"cryptoTokenValue,omitempty"`

	DestinationAddress string `json:"destinationAddress,omitempty"`

	Sender string `json:"sender,omitempty"`

	Recipient string `json:"recipient,omitempty"`

	ExpiresAt string `json:"expiresAt,omitempty"`
}
