/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddRiskProfileRequest struct {

	ClientId string `json:"clientId"`

	IsPep string `json:"isPep,omitempty"`

	IsUSCitizen string `json:"isUSCitizen,omitempty"`

	Gender string `json:"gender,omitempty"`

	InvestmentProjectedTrade string `json:"investmentProjectedTrade,omitempty"`

	InvestmentKnowledgeLevel string `json:"investmentKnowledgeLevel,omitempty"`

	InvestmentFinancialGoal string `json:"investmentFinancialGoal,omitempty"`

	InvestmentRiskAppetite string `json:"investmentRiskAppetite,omitempty"`

	InvestmentLiquidityNeeds string `json:"investmentLiquidityNeeds,omitempty"`
}
