/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Register struct {

	AuthCode *string `json:"authCode,omitempty"`

	Token *string `json:"token,omitempty"`
}
