/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetSystemHealthResponseModules struct {

	Fiat bool `json:"fiat,omitempty"`

	Trade bool `json:"trade,omitempty"`

	Crypto bool `json:"crypto,omitempty"`

	Admin bool `json:"admin,omitempty"`

	Ledger bool `json:"ledger,omitempty"`

	UserManagement bool `json:"user_management,omitempty"`
}
