/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatInRequestBody struct {

	Amount float32 `json:"amount,omitempty"`
}
