/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatInRequestResponseActionForm struct {

	ActionFormType string `json:"actionFormType,omitempty"`

	RedirectionUrl string `json:"redirectionUrl,omitempty"`
}
