/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponseUserInfo struct {

	FirstName string `json:"firstName,omitempty"`

	MiddleName string `json:"middleName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	BirthDate string `json:"birthDate,omitempty"`

	NameSuffix string `json:"nameSuffix,omitempty"`

	Sex string `json:"sex,omitempty"`

	Nationality string `json:"nationality,omitempty"`

	ContactNo string `json:"contactNo,omitempty"`

	EmailAdress string `json:"emailAdress,omitempty"`

	BirthCountry string `json:"birthCountry,omitempty"`

	BirthCity string `json:"birthCity,omitempty"`

	IncomeSource string `json:"incomeSource,omitempty"`

	SubmittedId string `json:"submittedId,omitempty"`

	GovernmentId string `json:"governmentId,omitempty"`

	GovernmentIdInfo string `json:"governmentIdInfo,omitempty"`
}
