/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatInRequestResponse struct {

	ActionForm FiatInRequestResponseActionForm `json:"actionForm,omitempty"`

	PaymentId string `json:"paymentId,omitempty"`

	Result FiatInRequestResponseResult `json:"result,omitempty"`
}
