/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatRequestResponseResponseBody struct {

	Transid string `json:"transid,omitempty"`

	Code float32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
