/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponseOtpStatus struct {

	IsLocked bool `json:"isLocked,omitempty"`

	Retries float32 `json:"retries,omitempty"`

	LastUpdated string `json:"lastUpdated,omitempty"`
}
