/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatRequestResponse struct {

	Response FiatRequestResponseResponse `json:"response,omitempty"`

	Signature string `json:"signature,omitempty"`
}
