/*
 * PDAX
 *
 * PDAX Integration with GCash
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FiatRequestResponseResponseHead struct {

	ClientId string `json:"clientId,omitempty"`

	RespTime string `json:"respTime,omitempty"`

	ReqMsgId string `json:"reqMsgId,omitempty"`
}
